export const assetPaths = {
  background: '/assets/backgrounds/dirt.png',
  backgroundRed: '/assets/backgrounds/dirt-red.png',
  characterBlue: '/assets/characters/blue.png',
  characterPurple: '/assets/characters/purple.png',
  characterWhite: '/assets/characters/white.png',
  characterGray: '/assets/characters/gray.png',
  enemyAlien: '/assets/enemies/alien.png',
  enemyCrab: '/assets/enemies/crab.png',
  enemyBrute: '/assets/enemies/brute.png',
  enemyWizard: '/assets/enemies/wizard.png',
  enemyNailhead: '/assets/enemies/nailhead.png',
  enemyGravity: '/assets/enemies/gravity.png',
  enemyMiniboss: '/assets/enemies/miniboss.png',
  enemyBoss: '/assets/enemies/boss.png',
  machineGun: '/assets/weapons/machine-gun.png',
  shuriken: '/assets/weapons/shuriken.png',
  bat: '/assets/weapons/bat.png',
  dagger: '/assets/weapons/dagger.png',
  sword: '/assets/weapons/sword.png',
  grenade: '/assets/weapons/grenade.png',
  molotov: '/assets/weapons/molotov.png',
  lightsaber: '/assets/weapons/lightsaber.png',
  machete: '/assets/weapons/machete.png',
  bazooka: '/assets/weapons/bazooka.png',
  bomb: '/assets/weapons/bomb.png',
  enemyBoomerang: '/assets/weapons/enemy-boomerang.png',
  gravityGrenade: '/assets/weapons/gravity-grenade.png',
  gems: '/assets/pickups/gems.png',
  gemDarkBlue: '/assets/pickups/gem-dark-blue.png',
  gemLightBlue: '/assets/pickups/gem-light-blue.png',
  coin: '/assets/pickups/coin.png',
  coin10: '/assets/pickups/coin-10.png',
  magnet: '/assets/pickups/magnet.png',
  potion: '/assets/pickups/potion.png',
  uiCircle: '/assets/ui/circle.png',
  uiCircleOutline: '/assets/ui/circle-outline.png',
  uiSquare: '/assets/ui/square.png',
  uiPause: '/assets/ui/pause.png',
  uiPlay: '/assets/ui/play.png',
} as const;

export const iconUrlByKey: Readonly<Record<string, string>> = {
  'weapon-machine-gun': assetPaths.machineGun,
  'weapon-shuriken': assetPaths.shuriken,
  'weapon-bat': assetPaths.bat,
  'weapon-dagger': assetPaths.dagger,
  'weapon-sword': assetPaths.sword,
  'weapon-grenade': assetPaths.grenade,
  'weapon-molotov': assetPaths.molotov,
  'weapon-lightsaber': assetPaths.lightsaber,
  'weapon-machete': assetPaths.machete,
  'weapon-bazooka': assetPaths.bazooka,
  'weapon-bomb': assetPaths.bomb,
  'pickup-potion': assetPaths.potion,
  'ui-circle': assetPaths.uiCircle,
  'ui-square': assetPaths.uiSquare,
  'ui-play': assetPaths.uiPlay,
};

export function iconUrl(key: string): string {
  return iconUrlByKey[key] ?? assetPaths.uiSquare;
}
